version: '3.4'

services:
  gateway.api:
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

  helpdesksupport.service:
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80

  authorize.service:
    ports:
      - "4000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    external:
      name: nat


